name: Build APK

on:
  push:
    branches:
      - main   # Triggers workflow on push to main branch
  pull_request:
    branches:
      - main   # Optional: Triggers workflow on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-11-jdk libncurses5
        pip install --upgrade pip
        pip install buildozer cython

    # Step 4: Build the APK using Buildozer
    - name: Build APK
      run: |
        # Initialize Buildozer (only if buildozer.spec doesn't exist)
        if [ ! -f buildozer.spec ]; then buildozer init; fi
        # Build the APK
        buildozer -v android debug

    # Step 5: Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyKivyApp-APK
        path: bin/*.apk   # Path to the APK generated by Buildozer
